export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'

export const GET_BRIEF_REQUEST = 'GET_BRIEF_REQUEST'
export const GET_BRIEF_SUCCESS = 'GET_BRIEF_SUCCESS'

export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST'
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS'

export const SET_TARGET_COUNTRY = 'SET_TARGET_COUNTRY'

export const GET_TIMESERIES_REQUEST = 'GET_TIMESERIES_REQUEST'
export const GET_TIMESERIES_SUCCESS = 'GET_TIMESERIES_SUCCESS' 

export const SET_TARGET_TIMESERIES_COUNTRY = 'SET_TARGET_TIMESERIES_COUNTRY'